<?php

namespace ademBundle\Repository;

/**
 * DemandeRepository.php
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends \Doctrine\ORM\EntityRepository
{

    public function getDemande()
    {
        /*$em = $this->getDoctrine()->getManager();
        $RAW_QUERY = 'select r.idRealisation as id, f.nom as filmnom,a.nom as acteurnom ,f.id as idfilm from film f JOIN realisation r on r.idfilm=f.id join acteur a on r.idacteur=a.id';
        $statement = $em->getConnection()->prepare($RAW_QUERY);
        $statement->execute();
        return $statement->fetchAll();*/
        $query = $this->getEntityManager()
            ->createQuery("SELECT d.iddemande as id, u.username as nom ,s.nom as salle ,d.datedemande as date ,d.besoin as besoin ,d.etat as etat from ademBundle:User u JOIN ademBundle:Demande d WITH d.iduser = u.id join ademBundle:Salle s WITH d.idsalle=s.id");
        return $query->getResult();

    }

}
