<?php

namespace ademBundle\Repository;

/**
 * EmpruntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpruntRepository extends \Doctrine\ORM\EntityRepository
{

    public function getEmprunt($idlivre ,$iduser)
    {

        $query = $this->createQueryBuilder('e')
            ->where('e.id_user = :iduser')
            ->andWhere('e.id_livre = :idlivre')
            ->setParameters(array(
                    'iduser'=>$iduser,
                    'idlivre'=>$idlivre,
                )
            )
            ->getQuery();
        return $query->getResult();
    }

    public function getEmprunts()
    {

        $query = $this->getEntityManager()
            ->createQuery("SELECT e.id_emprunt as id, u.username as nom , u.email as mail ,l.titreLivre as titrelivre ,l.id_livre as idlivre ,e.d_emprunt as dateEmprunt ,e.d_retour as dateRetour from ademBundle:User u JOIN ademBundle:EmpruntLivre e WITH e.id_user=u.id join ademBundle:Livre l WITH e.id_livre=l.id_livre");
        return $query->getResult();

    }



    public function getlivreEmprunts()
    {

        $query = $this->getEntityManager()

            ->createQuery("select l.titreLivre as titre, count(l.id_livre) as cnt from ademBundle:EmpruntLivre el join ademBundle:Livre l WITH el.id_livre=l.id_livre group by l.id_livre order by cnt DESC");
        return $query->getResult();

    }



}
