<?php
namespace ademBundle\Repository;

/**
 * EventSponsorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventSponsorRepository extends \Doctrine\ORM\EntityRepository
{


    public function getSponsorisation()
    {

        $query = $this->getEntityManager()
            ->createQuery("SELECT s.ideventsponsor as id, e.nom as nonevenement ,sp.nom as nomsponsor ,e.idevent as idevenemt from ademBundle:Evenement e JOIN ademBundle:Eventsponsor s WITH s.idevenement=e.idevent join ademBundle:Sponsor sp WITH s.idSponsors=sp.idsponsors");
        return $query->getResult();

    }


}