<?php

namespace ademBundle\Repository;

use ademBundle\Entity\Film;
use ademBundle\Entity\User;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
        public function getRating($idfilm ,$iduser)
        {

            $query = $this->createQueryBuilder('r')
                          ->where('r.id_user = :iduser')
                          ->andWhere('r.id_film = :idfilm')
                          ->setParameters(array(
                                                'iduser'=>$iduser,
                                                'idfilm'=>$idfilm,
                                                )
                                            )
                          ->getQuery();
            return $query->getResult();
        }

}

