<?php

namespace ademBundle\Repository;

/**
 * RealisationRepository.php
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getRealisation()
    {
        /*$em = $this->getDoctrine()->getManager();
        $RAW_QUERY = 'select r.idRealisation as id, f.nom as filmnom,a.nom as acteurnom ,f.id as idfilm from film f JOIN realisation r on r.idfilm=f.id join acteur a on r.idacteur=a.id';
        $statement = $em->getConnection()->prepare($RAW_QUERY);
        $statement->execute();
        return $statement->fetchAll();*/
        $query = $this->getEntityManager()
            ->createQuery("SELECT r.idrealisation as id, f.nom as filmnom ,a.nom as acteurnom ,f.id as idfilm from ademBundle:Film f JOIN ademBundle:Realisation r WITH r.idfilm=f.id join ademBundle:Acteur a WITH r.idacteur=a.id");
        return $query->getResult();

    }

}
