esprit_api:
    resource: "@EspritApiBundle/Resources/config/routing.yml"
    prefix:   /api

adem:
    resource: "@ademBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

pianosolo_weather:
    resource: "@PianoSoloWeatherBundle/Resources/config/routing.yml"

dwr_open_weather:
    resource: "@DwrOpenWeatherBundle/Controller/"
    type:     annotation
